#!/usr/bin/env bash

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source ./link${COLOR_NC}"
else

  link (){
    if [ -e $1 ]; then
      if [ -e $2 ]; then
        rm $2
      fi

      ln -s $1 $2
    fi
  }

  # bash
  link ~/Code/dotfiles/etc/bash_profile ~/.bash_profile
  link ~/Code/dotfiles/etc/bashrc ~/.bashrc
  link ~/Code/dotfiles/etc/bashrc_help ~/.bashrc_help
  link ~/Code/dotfiles/etc/bashrc_app_specific ~/.bashrc_app_specific

  # vim
  link ~/Code/dotfiles/etc/vim/vimrc ~/.vimrc
  link ~/Code/dotfiles/etc/vim/gvimrc ~/.gvimrc
  link ~/Code/dotfiles/etc/vim ~/.vim

  # git
  link ~/Dropbox/mac_env/gitconfig ~/.gitconfig
  link ~/Code/dotfiles/etc/gitignore ~/.gitignore
  link ~/Code/dotfiles/etc/gitattributes ~/.gitattributes

  # misc
  link ~/Code/dotfiles/etc/autotest ~/.autotest
  link ~/Code/dotfiles/etc/irbrc ~/.irbrc
  link ~/Dropbox/mac_env/dot_ssh/config ~/.ssh/config

  source ~/.bash_profile

fi
